# Q
# GitHub Actions 脚本_利用 GitHub Actions 来下载并运行 uupdump 脚本、以此来获取 Windows 的 iso 文件。
# 编辑日期：2023年7月11日
# A
name: Run uupdump script to get Windows 11 iso file and upload it to OneDrive

on: [push]

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - name: Doploy uupdump
        # 在 PowerShell 环境下，(1)下载 uupdump zip 压缩文件，(2)解压
        shell: powershell
        run: |
          Invoke-WebRequest "https://github.com/tonyank/20221226-uupdump/raw/main/26100.1591_amd64_zh-cn_professional_df9477d8_convert.tar"
          tar -xf "26100.1591_amd64_zh-cn_professional_df9477d8_convert.tar"

      - name: Run uupdump
        shell: powershell
        run: ./uup_download_windows.cmd
        
      - name: Deploy rclone
        shell: pwsh
        run: |
          Invoke-WebRequest 'https://downloads.rclone.org/v1.67.0/rclone-v1.67.0-windows-amd64.zip' -OutFile rclone-v1.67.0-windows-amd64.zip
          unzip rclone-v1.67.0-windows-amd64.zip
          echo '${{ secrets.RCLONE_CONF }}' > rclone.conf

      - name: Upload the file to OneDrive with rclone
        shell: powershell
        run: rclone-v1.67.0-windows-amd64/rclone --config rclone.conf copy -P *.iso 'OneDrive_ty_30GB:'
